### ISSUE TITLE
[Question] Different sizes

### ISSUE THREAD

**Issue by TimothieGeulin** [jewettaij/superpose3d_cpp#1]
Does it work with 2 point cloud that aren't the same size?
I'm running into an error and I suppose that the unmatching sizes are the source.

![Sans titre 1](https://user-images.githubusercontent.com/31931443/83662515-e0fd6800-a5c7-11ea-96e4-152c99d887ce.png)

Is that it? Is there a way to prevent that kind of problem?

EDIT: That's it, it works when I alloc the same size for both, I didn't expect it to be limited to 2 clouds of the same size... I tried putting the same datas again and again to fill the smaller one but the results weren't good...

**Comment by jewettaij** [comment]
From the README.md file:

"Superpose(), which takes as arguments two N×3 arrays representing two ordered sets of points"

The two point clouds must be the same size (N).  Furthermore, the two point clouds must be *ordered*.  (That is the 1st point in cloud1 must correspond to the 1st point in cloud2.  The 2nd point in cloud 1 must correspond to the 2nd point in cloud2...)  The equation for RMSD also clarifies this.

Superimposing point clouds of differing sizes is an ill-posed problem.  There are various ways to solve it if you are willing to accept sub-optimal assignments, and/or if you are willing additional assumptions about the way the data is being used.  (I worked on [one of these methods](http://www.rbvi.ucsf.edu/Research/projects/minrms), but it is really only suitable for comparing protein structures, so I would not recommend it for you.)  Check out the [wikipedia article on "point set registration"](https://en.wikipedia.org/wiki/Point_set_registration).  Also read about the ["iterative closest point" algorithm](https://en.wikipedia.org/wiki/Iterative_closest_point).   This [paper](https://arxiv.org/abs/2001.07715) may also be useful. (It is reference 19 from the first wikipedia article.)

I appreciate the feedback.  If I have time, perhaps I'll try and clarify this in the README.md file.
-Andrew
